### ISSUE TITLE
No less than 30 seconds

### ISSUE THREAD

**Issue by terreng** [EvolSoft/Broadcaster#1]

**Comment by Flavius12** [comment]
Thank you for report. I noticed that I didn't add the time update after configuration reload.
This bug will be fixed soon ;)

**Comment by JoahDave** [comment]
Yay! I helped!

**Comment by Flavius12** [comment]
Fixed in v1.15!
Thank you for bug report! :+1:

**Comment by JoahDave** [comment]
Follow me?

**Comment by Flavius12** [comment]
In what?

**Comment by JoahDave** [comment]
GitHub

**Comment by JoahDave** [comment]
Im working on some pretty nice plugins. I just released one called MyHealth to set a players health to what you want. It's pretty cool!
