### ISSUE TITLE
Broadcaster is spamming chat!

### ISSUE THREAD

**Issue by DjJakkiGlass** [EvolSoft/Broadcaster#2]
Dude, I can't figure out how to slow down the messages. I set the interval to 1200
and duration to 3. Please help!

**Comment by Flavius12** [comment]
You must reload the plugin after saving configuration file. Do /bc reload and let me know if it works

**Comment by DjJakkiGlass** [comment]
It's still sending pop ups too fast. Plus I tried to set it for just one message..and it's doing the one message plus broadcasting the others as message 2 and message 3. I deleted the other 2 and reloaded and it's still posting them even though they aren't there.

On July 20, 2015, at 3:23 AM, Flavius12 notifications@github.com wrote:

You must reload the plugin after saving configuration file. Do /bc reload and let me know if it works
